# This allows only Deployment main container should have image DIGEST instead of tags
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: deployment-main-container-must-use-digest
spec:
  # Reject non-compliant deployments
  validationFailureAction: Enforce
  
  # Check only new/updated resources
  background: false

  rules:
    - name: validate-main-container-image-digest
      match:
        any:
          - resources:
              kinds:
                - Deployment
      validate:
        message: >-
          Deployment main container image must use immutable digest
          format image@sha256:<digest> instead of image tags.
        deny:
          conditions:
            all:
              # Get first container image (main application container)
              - key: "{{ request.object.spec.template.spec.containers[0].image }}"
                operator: NotEquals
                value: "{{ regex_match('.*@sha256:.*', request.object.spec.template.spec.containers[0].image) }}"
