name: CI/CD — backend

# Triggers on push to develop / release branches only.
# Feature branches and PRs → ci-pr-api-gateway.yml
#
# Jobs:
#   build       → Maven + SAST + Docker + ECR + Cosign
#   deploy-dev  → direct commit to envs/dev/ → ArgoCD auto-syncs → smoke test
#   open-qa-pr  → opens a PR in zen-gitops for envs/qa/ (PR merge = QA deployment)
#
#
# PROD promotion → promote-prod.yml (workflow_dispatch)

on:
  push:
    branches: [develop, 'release/**']
    paths:
      - 'backend/**'
      - '.github/workflows/02-ci-backend.yml'

permissions:
  id-token: write
  contents: read
  security-events: write
  actions: read

env:
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  AWS_REGION: us-east-1
  ECR_REPOSITORY: backend
  GITOPS_REPO: ${{ vars.GITOPS_REPO }}

jobs:
  Ecr-Uri-Job:
    name: Construct ECR URI
    runs-on: ubuntu-latest
    
    outputs:
      ecr-uri: ${{ steps.ecr-uri.outputs.ecr-uri }}
      
    steps:
      - name: Construct ECR URI
        id: ecr-uri
        run: |
          ECR_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY"
          echo "ecr-uri=$ECR_URI" >> "$GITHUB_OUTPUT"
        
  Build-Job: 
    name: Build Job
    needs: [Ecr-Uri-Job]
    uses: ./.github/workflows/_go-build.yml
    with: 
      service-name: backend
      
      # --------------------------------------------
      # Sonarqube Scan
      # --------------------------------------------
      sonarqube-scan: true
      sonar-host-url: ${{ vars.SONAR_HOST_URL }}
    
       # --------------------------------------------
      # Docker Image Build
      # --------------------------------------------
      dockerfile: backend/Dockerfile
      build-context: backend
      ecr-uri: ${{ needs.Ecr-Uri-Job.outputs.ecr-uri }}

      arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/shopverse-dev-github-actions-role
      shopverse-dev-github-actions-role

    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
