name: CI/CD — backend

# Triggers on push to develop / release branches only.
# Feature branches and PRs → ci-pr-api-gateway.yml
#
# Jobs:
#   build       → Maven + SAST + Docker + ECR + Cosign
#   deploy-dev  → direct commit to envs/dev/ → ArgoCD auto-syncs → smoke test
#   open-qa-pr  → opens a PR in zen-gitops for envs/qa/ (PR merge = QA deployment)
#
#
# PROD promotion → promote-prod.yml (workflow_dispatch)

on:
  push:
    branches: [develop, 'release/**']
    paths:
      - 'backend/**'
      - '.github/workflows/02-ci-backend.yml'

permissions:
  id-token: write
  contents: read
  security-events: write
  actions: read

env:
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  AWS_REGION: us-east-1
  AWS_ECR_ROLE_ARN: ${{ vars.AWS_ECR_ROLE_ARN }}  # arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/shopverse-dev-github-actions-role
  ECR_REPOSITORY: backend
  GITOPS_REPO: ${{ vars.GITOPS_REPO }}

jobs:
  Aws-Params-Job:
    name: AWS Parameters
    runs-on: ubuntu-latest
    
    outputs:
      ecr-registry: ${{ steps.aws-params.outputs.ecr-registry }}
      ecr-repository: ${{ steps.aws-params.outputs.ecr-repository }}
      aws-region: ${{ steps.aws-params.outputs.aws-region }}
      aws-ecr-role-arn: ${{ steps.aws-params.outputs.aws-ecr-role-arn }}
      
    steps:
      - name: Construct ECR Registry
        id: aws-params
        run: |
          ECR_REGISTRY="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
          
          echo "ecr-registry=$ECR_REGISTRY" >> "$GITHUB_OUTPUT"
          echo "ecr-repository=$ECR_REPOSITORY" >> "$GITHUB_OUTPUT"
          echo "aws-region=$AWS_REGION" >> "$GITHUB_OUTPUT"
          echo "aws-ecr-role-arn=$AWS_ECR_ROLE_ARN" >> "$GITHUB_OUTPUT"
        
  CI-Job: 
    name: CI Job
    needs: [Aws-Params-Job]
    uses: ./.github/workflows/_go-build.yml
    with: 
      service-name: backend      # ${{ needs.Aws-Params-Job.outputs.ecr-repository }}
      runner: ubuntu-latest
      
      gitleaks-scan: true
      trivy-fs-scan: true
      codeql-scan: false
      sonarqube-scan: false
      sonar-host-url: ""        # ${{ vars.SONAR_HOST_URL }}

      image-build: false
      dockerfile: backend/Dockerfile
      build-context: backend
      
      trivy-dockerfile-scan: false
      hadolint-dockerfile-scan: false
      opa-conftest-dockerfile-scan: false

      image-sign: false
      image-sbom: false
      
      ecr-registry: ${{ needs.Aws-Params-Job.outputs.ecr-registry }}
      ecr-repository: ${{ needs.Aws-Params-Job.outputs.ecr-repository }}
      aws-region: ${{ needs.Aws-Params-Job.outputs.aws-region }}
      aws-ecr-role-arn: ${{ needs.Aws-Params-Job.outputs.aws-ecr-role-arn }}
      

    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
