name: CI - Backend

on:
  push:
    branches:
      - develop
      - 'release/**'
    paths:
      - 'backend/**'
      - '.github/workflows/ci-backend.yml'

jobs:
  Pr-Check-Job:
    uses: ./.github/workflows/_02-go-pr-check.yml
    with:
      service-name: backend
