name: CI - Backend

on:
  push:
    branches: ['feat-*', 'fix-*', 'chore-*']
    paths:
      - 'backend/**'
      - '.github/workflows/_01-ci-pr-backend.yml'

jobs:
  Pr-Check-Job:
    uses: ./.github/workflows/_02-go-pr-check.yml
    with:
      service-name: backend
