name: Reusable — GO PR Check (no Docker)

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string

      sonarqube-scan:
        description: "Enable SonarQube Scan"
        required: false
        type: boolean
        default: false

      sonar-host-url:
        required: false
        type: string
        default: ""

      runner:
        description: "Runner label"
        required: false
        type: string
        default: ubuntu-latest

    secrets:
      SONAR_TOKEN:
        required: false    
  
jobs:
  
  Gitleaks-Job:
    name: Gitleaks
    uses: ./.github/workflows/reusable-gitleaks.yml
    with:
      service-name: ${{ inputs.service-name }} 
    # secrets: inherit

  Sonarqube-Job:
    if: ${{ inputs.sonarqube-scan }}
    name: Sonarqube
    uses: ./.github/workflows/reusable-sonarqube.yml
    with:
      service-name: ${{ inputs.service-name }} 
      sonar-host-url: ${{ inputs.sonar-host-url }}
            
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  Trivy-Fs-Scan-Job:
    name: Trivy Fs Scan
    uses: ./.github/workflows/reusable-trivy-fs.yml
    with:
      service-name: ${{ inputs.service-name }}

  Codeql-Analysis-Job:
    name: Codeql Analysis
    uses: ./.github/workflows/reusable-codeql.yml
    with:
      service-name: ${{ inputs.service-name }}
