name: Reusable — GO PR Check (no Docker)

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
  
jobs:
  
  Gitleaks-Job:
    name: Gitleaks
    uses: ./.github/workflows/reusable-gitleaks.yml
    with:
      service-name: ${{ inputs.service-name }} 
    # secrets: inherit

  Sonarqube-Job:
    name: Sonarqube
    uses: ./.github/workflows/reusable-sonarqube.yml
    with:
      service-name: ${{ inputs.service-name }} 
      sonar-host-url: ${{ vars.SONAR_HOST_URL }}
            
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  Trivy-Fs-Scan-Job:
    name: Trivy Fs Scan
    uses: ./.github/workflows/reusable-trivy-fs.yml
    with:
      service-name: ${{ inputs.service-name }}

  Codeql-Analysis-Job:
    name: Codeql Analysis
    uses: ./.github/workflows/reusable-codeql.yml
    with:
      service-name: ${{ inputs.service-name }}
