# Reusable — Go Build + SAST + Container Security + ECR Push + Cosign Sign
name: Reusable — GO Build & Security Gates

on:
  workflow_call:
    inputs:
      service-name:
        description: "Service Name"
        required: true
        type: string

      runner:
        description: "Runner label"
        required: false
        type: string
        default: ubuntu-latest

      # ---------------- Scans ------------------------- #
      gitleaks-scan:
        description: "Enable Gitleaks Scan"
        required: true
        type: boolean
        default: false
        
      trivy-fs-scan:
        description: "Enable Trivy FS Scan"
        required: true
        type: boolean
        default: false
        
      codeql-scan:
        description: "Enable CodeQL Scan"
        required: true
        type: boolean
        default: false

      sonarqube-scan:
        description: "Enable Sonarqube Scan"
        required: true
        type: boolean
        default: false

      sonar-host-url:
        description: "Sonarqube Host Url"
        required: true
        type: string
        default: ""

      # --------------- Dockerfile $ Scans --------------------- #
      dockerfile-scan:
        description: "Enable Dockerfile Scan"
        required: true
        type: boolean
        default: false

      dockerfile:
        description: "Path to Dockerfile"
        required: true
        type: string
        default: ""

      build-context:
        description: "Image build context"
        required: true
        type: string
        default: ""

      hadolint-dockerfile-scan:
        description: "Enable Hadolint Dockerfile Scan"
        required: true
        type: boolean
        default: false

      trivy-dockerfile-scan:
        description: "Enable Trivy Dockerfile Scan"
        required: true
        type: boolean
        default: false

      opa-conftest-dockerfile-scan:
        description: "Enable OPA conftest Dockerfile Scan"
        required: true
        type: boolean
        default: false
      # --------------- Image Build ------------------------- #
      image-build:
        description: "Enable Image Build"
        required: true
        type: boolean
        default: false
      # ----------------------------------------------------- #
      ecr-registry:
        description: "ECR Registry URL"
        required: true
        type: string
        default: ""

      ecr-repository:
        description: "ECR Repository"
        required: true
        type: string
        default: ""

      aws-region:
        description: "AWS Region to push Docker Image"
        required: true
        type: string
        default: ""

      aws-ecr-role-arn:
        description: "Role ARN to push ECR Image"
        required: true
        type: string
        default: ""

      image-sign:
        description: "Enable Image Signing"
        required: true
        type: boolean
        default: false

      image-sbom:
        description: "Enable SBOM generation"
        required: true
        type: boolean
        default: false

      helm-values-file:
        description: "Helm Values File"
        required: true
        type: string
        default: ""

      # --------------- Helm Values Update ----------------------- #
      gitops-repo:
        description: "GitOps Repository"
        required: true
        type: string

      helm-values-file:
        description: "Path to Helm values.yaml inside GitOps repo"
        required: true
        type: string

      image:
        description: "Container image repository"
        required: true
        type: string

      image-digest:
        description: "Image Digest"
        required: true
        type: string
    
    # --------------------------- Secrets ------------------------ # 
    secrets:
      SONAR_TOKEN:
        required: false

      GITOPS_TOKEN:
        required: true

jobs:

  Pr-Check-Job:
    name: PR Check Job
    uses: ./.github/workflows/_go-pr-check.yml
    with:
      service-name: ${{ inputs.service-name }}
      runner: ${{ inputs.runner }}
      sonarqube-scan: ${{ inputs.sonarqube-scan }}
      sonar-host-url: ${{ inputs.sonar-host-url }}
      gitleaks-scan: ${{ inputs.gitleaks-scan }}
      trivy-fs-scan: ${{ inputs.trivy-fs-scan }}
      codeql-scan: ${{ inputs.codeql-scan }}

    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  Dockerfile-Scan-Job:
    if: ${{ inputs.dockerfile-scan }}
    name: Dockerfile Scan Job
    uses: ./.github/workflows/reusable-dockerfile-scan.yml
    with:
      service-name: ${{ inputs.service-name }}
      runner: ${{ inputs.runner }}
      dockerfile: ${{ inputs.dockerfile }}
      hadolint-dockerfile-scan: ${{ inputs.hadolint-scan }}
      trivy-dockerfile-scan: ${{ inputs.trivy-scan }}
      opa-conftest-dockerfile-scan: ${{ inputs.opa-conftest-scan }}

  Image-Build-Scan-Push-Job:
    if: ${{ inputs.image-build }}
    name: Docker Image Build-Scan-Push Job
    needs:
      - Pr-Check-Job
      - Dockerfile-Scan-Job
    uses: ./.github/workflows/reusable-image-build.yaml
    with:
      service-name: ${{ inputs.service-name }}
      runner: ${{ inputs.runner }}
      dockerfile: ${{ inputs.dockerfile }}
      build-context: ${{ inputs.build-context }}
      ecr-registry: ${{ inputs.ecr-registry }}
      ecr-repository: ${{ inputs.ecr-repository }}
      aws-region: ${{ inputs.aws-region }}
      aws-ecr-role-arn: ${{ inputs.aws-ecr-role-arn }}

  Image-Sign-Job:
    if: ${{ inputs.image-sign }}
    name: Image Sign
    needs: 
      - Image-Build-Scan-Push-Job
    uses: ./.github/workflows/reusable-image-sign.yml
    with:
      service-name: ${{ inputs.service-name }}
      runner: ${{ inputs.runner }}
      image-with-digest: ${{ needs.Image-Build-Job.outputs.image_with_digest }}
      aws-region: ${{ inputs.aws-region }}
      aws-ecr-role-arn: ${{ inputs.aws-ecr-role-arn }}

  Generate-Attest-SBOM-Job:
    if: ${{ inputs.image-sbom }}
    name: Generate and Attest SBOM
    needs:
      - Image-Build-Scan-Push-Job
    uses: ./.github/workflows/reusable-sbom.yml
    with:
      service-name: ${{ inputs.service-name }}
      runner: ${{ inputs.runner }}
      image-with-digest: ${{ needs.Image-Build-Job.outputs.image_with_digest }}
      aws-region: ${{ inputs.aws-region }}
      aws-ecr-role-arn: ${{ inputs.aws-ecr-role-arn }}

  Update-Helm-Values-Pr-Job:
  name: Update Helm Values and create PR
  needs:
    - Image-Build-Scan-Push-Job
  uses: ./.github/workflows/reusable-update-helm-values.yml
  with:
    service-name: ${{ inputs.service-name }}
    runner: ${{ inputs.runner }}
    gitops-repo: ${{ inputs.gitops-repo }}
    helm-values-file: ${{ inputs.helm-values-file }}  # envs/dev/backend/values.yaml
    image: ${{ needs.Image-Build-Scan-Push-Job.outputs.image }}
    image-digest: ${{ needs.Image-Build-Scan-Push-Job.outputs.image_digest }}

  
