name: Reusable - Gitleaks

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string

jobs:
  gitleaks:
    name: Gitleaks
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: results.sarif
          category: gitleaks-${{ inputs.service-name }}
