name: Reusable - Docker Image Build

on:
  workflow_call:
    inputs:
      runner:
        description: "Runner label"
        required: false
        type: string
        default: ubuntu-latest
      
      dockerfile:
        description: "Path to Dockerfile"
        required: true
        type: string

      build-context:
        description: "Image build context"
        required: true
        type: string

      ecr-uri:
        description: "Complete ECR URI"
        required: true
        type: string

    outputs:
      image_with_tag:
        description: "Complete ECR image URI with tag"
        value: ${{ jobs.Image-Build-Job.outputs.image_with_tag }}

jobs:
  Image-Build-Job:
    name: Build Docker Image
    runs-on: ${{ inputs.runner }}

    permissions:
      contents: read

    outputs:
      image_with_tag: ${{ steps.image-build.outputs.image_with_tag }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set Image Tag
        id: meta
        run: |
          echo "image_tag=sha-${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Build Image
        id: image-build
        run: |
          IMAGE_WITH_TAG="${{ inputs.ecr-uri }}:${{ steps.meta.outputs.image_tag }}"

          docker build \
            -t "$IMAGE_WITH_TAG" \
            -f "${{ inputs.dockerfile }}" \
            "${{ inputs.build-context }}"

          echo "image_with_tag=$IMAGE_WITH_TAG" >> "$GITHUB_OUTPUT"
