name: Reusable - Dockerfile Scan

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string

      dockerfile-path:
        description: "Dockerfile with complete path"
        required: true
        type: string

      runner:
        description: "Runner label"
        required: false
        type: string
        default: ubuntu-latest

      hadolint-scan:
        required: false
        type: boolean
        default: false
        
      trivy-scan:
        required: false
        type: boolean
        default: false

      opa-conftest-scan:
        required: false
        type: boolean
        default: false

      opa-policy-file-path:
        description: "Policy file with complete path"
        required: false
        type: string
        
jobs:
  Dockerfile-Scan-Job:
    name: Dockerfile Scan
    runs-on: ${{ inputs.runner }}

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Verify Dockerfile
        run: |
          test -f "${{ inputs.dockerfile-path }} || {
            echo "Dockerfile not found: ${{ inputs.dockerfile-path }}"
            exit 1
          }
          
      - name: Hadolint scan
        if: ${{ inputs.hadolint-scan }}
        uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: ${{ inputs.service-name }}/Dockerfile
          failure-threshold: error

      - name: Trivy Dockerfile Scan
        if: ${{ inputs.trivy-scan }}
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          version: v0.72.0
          scan-type: config
          scan-ref: ${{ inputs.service-name }}/Dockerfile
          format: sarif
          output: trivy-${{ inputs.service-name }}-dockerfile.sarif
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 0   # 1

      - name: Install Conftest
        if: ${{ inputs.opa-conftest-scan }}
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/latest/download/conftest_Linux_x86_64.tar.gz
          tar xzf conftest_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin/

      - name: OPA Policy Check
        if: ${{ inputs.opa-conftest-scan }}
        run: conftest test ${{ inputs.dockerfile-path }} --policy {{ inputs.opa-policy-file-path }}

      - name: Upload Trivy Dockerfile SARIF
        if: ${{ always() && inputs.trivy-scan }}
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-${{ inputs.service-name }}-dockerfile.sarif
          category: trivy-dockerfile-${{ inputs.service-name }}
