apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-allowed-registries
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: restrict-main-container-registries
      match:
        any:
          - resources:
              kinds:
                - Deployment

      validate:
        message: >-
          Deployment main container image must come from approved ECR registries
          (123456789012.dkr.ecr.us-east-1.amazonaws.com,
           123456789012.dkr.ecr.eu-west-1.amazonaws.com)

        foreach:
          - list: "request.object.spec.template.spec.containers[0]"
            deny:
              conditions:
                all:
                  - key: "{{ element.image }}"
                    operator: NotMatches
                    value: >-
                      ^(123456789012\.dkr\.ecr\.us-east-1\.amazonaws\.com|
                        123456789012\.dkr\.ecr\.eu-west-1\.amazonaws\.com)/.+
