apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-deployment-image-digest
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: check-digest
      match:
        any:
          - resources:
              kinds:
                - Deployment
      validate:
        message: "Image must use digest"
        foreach:
          - list: "request.object.spec.template.spec.containers[0]"
            deny:
              conditions:
                any:
                  - key: "{{ element.image }}"
                    operator: NotMatches
                    value: ".*@sha256:[a-f0-9]{64}$"
