apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-image-signature
spec:
  validationFailureAction: Enforce
  background: false

  rules:
  - name: verify-cosign-signature
    match:
      any:
      - resources:
          kinds:
          - Pod
    verifyImages:
    - imageReferences:
      - "123456789012.dkr.ecr.us-east-1.amazonaws.com/*"
    # - "*.dkr.ecr.*.amazonaws.com/*"
      mutateDigest: true
      attestors:
      - count: 1
        entries:
        - keyless:
            issuer: https://token.actions.githubusercontent.com
            subject: >-
              repo:YOUR_ORG/YOUR_REPO:.github/workflows/docker-build.yaml@refs/heads/main
            # subject: "repo:your-org/app-repo:*"
            # subject: "https://github.com/vaheedgit26/devsecops:*"
            # subject: "https://github.com/vaheedgit26/devsecops:.github/workflows/docker-build.yaml@refs/heads/dev
            # Rekor transparency log (default public)
            rekor:
              url: https://rekor.sigstore.dev
