apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-sbom-attestation
spec:
  validationFailureAction: Enforce
  background: false
  rules:
  - name: verify-cyclonedx-sbom
    match:
      any:
      - resources:
          kinds:
          - Pod
    verifyImages:
    - imageReferences:
      - "123456789012.dkr.ecr.us-east-1.amazonaws.com/*"
      attestations:
      - predicateType: https://cyclonedx.org/schema
        attestors:
        - entries:
          - keyless:
              issuer: https://token.actions.githubusercontent.com
              subject: >-
                repo:YOUR_ORG/YOUR_REPO:.github/workflows/docker-build.yaml@refs/heads/main
              # subject: "repo:your-org/app-repo:*"
              # subject: "https://github.com/vaheedgit26/devsecops:*"
              # subject: "https://github.com/vaheedgit26/devsecops:.github/workflows/docker-build.yaml@refs/heads/dev
