name: Print name
on:
  push:
    branches: main
env:
  NAME: VAHEED
jobs:
  print-name-job:
    name: set name
    id: set-name
    run: echo "name = $NAME" >> "$GITHUB_OUTPUTS"
    
    name: print 
    uses: ./.github/workflows/reusable-print.yml
    with:
      name: ${{ steps.set-name.outputs.name}}
  
